#!/usr/bin/env bash

set -eu

cwd="$(cd "$(dirname "$0")" && pwd)"

fly --target ci \
    set-pipeline \
    --pipeline boclips-spring-web \
    --config "$cwd/pipeline.yml" \
    --var boclips-spring-web-repo-key="$(lpass show concourse-boclips-spring-web-repo-key --notes)"
